### ISSUE TITLE
Implement DIS package

### ISSUE THREAD

**Issue by tomvansteijn** [tomvansteijn/mf6brabant#1]

**Comment by tomvansteijn** [comment]
DIS package is written in notebooks\dis.ipynb, see 8584a37e843be73be4d30131d96de3505accb1ad

Number of layers in DIS package is 37 (nlay*2 - 1), due to conversion from quasi-3D to 3D.

**Comment by jvansijl** [comment]
> DIS package is written in notebooks\dis.ipynb, see [8584a37](https://github.com/tomvansteijn/mf6brabant/commit/8584a37e843be73be4d30131d96de3505accb1ad)
> 
> Number of layers in DIS package is 37 (nlay*2 - 1), due to conversion from quasi-3D to 3D.

als ik in de wel-package een CELLID opgeef (layer,row,column), begin je dan bij 0 of bij 1 te tellen?

**Comment by Hugovdberg** [comment]
De cell ID is zero-based, wordt in de input files voor MF6 automatisch met 1 verhoogd, zie de WEL package output uit onderstaand test scriptje:

```Python
from pathlib import Path

import flopy
import numpy as np

name = 'test_well'
ws = Path('./test_well')

# Create the Flopy simulation object
sim = flopy.mf6.MFSimulation(
    sim_name=name,
    exe_name='mf6', 
    version='mf6',
    sim_ws=str(ws))

# Create the Flopy temporal discretization object
tdis = flopy.mf6.modflow.mftdis.ModflowTdis(sim,
    pname='tdis',
    time_units='DAYS',
    nper=1, 
    perioddata=[(1.0, 1, 1.0)],
    )

# Create the Flopy groundwater flow (gwf) model object
model_nam_file = f'{name}.nam'
gwf = flopy.mf6.ModflowGwf(sim,
    modelname=name, 
    model_nam_file=model_nam_file,
)

dis = flopy.mf6.modflow.mfgwfdis.ModflowGwfdis(gwf,
    pname='dis', 
    nlay=1,
    nrow=1, ncol=1,
    delr=1, delc=1,
    top=1, botm=0,
    idomain=1,
)

wel = flopy.mf6.modflow.mfgwfwel.ModflowGwfwel(
    gwf,
    stress_period_data=[
        ((0,0,0), 1)
    ]
)

gwf.write()
```

**Comment by Hugovdberg** [comment]
@tomvansteijn Ik denk dat het slim is om de DIS package nog iets meer opties mee te geven, namelijk `length_units`, `xorigin` en `yorigin`. Voor de modelresultaten maakt het op zich niet uit, maar voor de postprocessing is het wel handig.

**Comment by tomvansteijn** [comment]
Hoi @Hugovdberg ,

Goed punt. Ga ik doen.
